spring:
  kafka:
    producer:
      bootstrap-servers: "localhost:9093"
      key-serializer: org.springframework.kafka.support.serializer.StringOrBytesSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
kafka:
  topic: "MESSAGE"
